### PR TITLE
Support ipuz v2

### PR DESCRIPTION
**Pull request by maiamcc**
Was using [`kpuz`](https://github.com/kberg/kpuz) to convert some of my puzzles (created via CrossFire) from ipuz -> puz; `kpuz` relies on this library, and things were breaking b/c CrossFire only knows how to export in ipuz v2 format. This PR adds support for ipuz v2 (though not for any additional kind-specific formats -- afaik they're all still on crossword v1, sudoku v1, etc.).

I know it's been a bit since you touched this, but I appreciate that it exists!!

### CODE REVIEW

**Comment by maiamcc** [comment]
Tests pass now! 😅 
Screen Shot 2020-09-29 at 7 09 49 PM

**Comment by svisser** [comment]
@maiamcc nice one! It's been a while since I looked at this library but I'll take a look and then we can merge it in :+1:

**Comment by maiamcc** [comment]
ping! Need this support for a project--any chance of this getting into a release, or should I use my fork of this repo instead?

**Comment by svisser** [comment]
@maiamcc hi there, as I haven't looked at this PR for a long time, I'm aware it may not look that way but I appreciate your work for adding support for ipuz v2! :tada: I have just looked at it in more detail, merged it in and also made a few additional library maintenance changes.

Python 3.5 has reached end-of-life so it's now Python 3.6+ only and I have also removed the `six` dependency as it's no longer needed. I bumped the version number to 1.0 as the library has remained stable for quite some time now and there are some larger changes included.

**Comment by maiamcc** [comment]
No worries, I know how it goes--I'm grateful that you're maintaining the library! 🙌

**Pull request merged**
